spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User?useSSL=false
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

   #  spring.datasource.tomcat.max-active=1