spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User
    username: root
    password: Hamster12!?
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    # spring.datasource.tomcat.max-active=1